services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend:${BACKEND_VERSION:-latest}
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_RELOAD: True
      BACKEND_DB_HOST: backend-db
      BACKEND_DB_PORT: 5432
      BACKEND_DB_USER: backend
      BACKEND_DB_PASS: backend
      BACKEND_DB_BASE: backend
      BACKEND_REDIS_HOST: backend-redis

  db:
    image: pgvector/pgvector:pg17
    hostname: backend-db
    environment:
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_DB: "backend"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U backend
      interval: 2s
      timeout: 3s
      retries: 40

  redis:
    image: bitnami/redis:6.2.5
    hostname: "backend-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  ollama:  # New service for running the Dockerfile in /ollama
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama
    ports: ["11434:11434"] # will be accessible in http://localhost:11435
    volumes:
      - ./model_files:/model_files  # Mount the directory with the trained 
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - ./myrules.yml:/myrules.yml
    command:
      - '--config.file=/prometheus.yml'

volumes:
  backend-db-data:
    name: backend-db-data
  ollama:
